name: CLI Unit Tests
on:
  push:
    branches: [ main ]
  pull_request:

env:
  ARTIFACTORY_URL: ${{ vars.ARTIFACTORY_URL }}

jobs:
  lockfile-hygiene:
    runs-on: ubuntu-x64
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: twilio/sdk-actions/npm-lockfile-hygiene@0375437914d535a5fb178bdbfdb5d51bdde2616e # v1
        with:
          package-manager: npm

  test:
    needs: [lockfile-hygiene]
    runs-on: ubuntu-x64
    if: github.repository_owner == 'twilio'
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 22.x, lts/* ]
    steps:
      - name: Checkout cli repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Artifactory OIDC Auth
        uses: twilio/sdk-actions/artifactory-oidc@23b656b843d2a3461cf38e4fd466c07a822d5fc0 # v1
      - run: make install
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Run tests
        run: npm test
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        if: (github.event_name == 'pull_request' || github.ref_type == 'branch') && !github.event.pull_request.head.repo.fork && matrix.node-version == 'lts/*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  notify-complete-fail:
    if: ${{ failure() && github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
    needs: [ test ]
    name: Notify Test Failed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.ALERT_SLACK_WEB_HOOK }}
          SLACK_COLOR: 'danger'
          SLACK_USERNAME: CLI Github Actions
          SLACK_MSG_AUTHOR: twilio-dx
          SLACK_ICON_EMOJI: ':github:'
          SLACK_TITLE: "Twilio Cli"
          SLACK_MESSAGE: 'Cli tests failed'
          MSG_MINIMAL: actions url
          SLACK_FOOTER: Posted automatically using GitHub Actions
