name: Docker Hub Release Rollback
on:
  workflow_dispatch:
    inputs:
      rollback_tag:
        description: 'Tag to set as latest'
        required: true
        default: ''
jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Pull desired tag
        run: docker pull twilio/twilio-cli:${{ github.event.inputs.rollback_tag }}
      - name: Tag as latest
        run: docker tag twilio/twilio-cli:${{ github.event.inputs.rollback_tag }} twilio/twilio-cli:latest
      - name: Push latest
        run: docker push twilio/twilio-cli:latest
