name: Cli Release Token Validation
on:
  workflow_dispatch:

jobs:
  token-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Validate REPO_ACCESS_TOKEN 
        uses: actions/checkout@v2
        with:
          repository: '${{ github.repository_owner }}/twilio-oai'
          token:  ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: Validate AWS tokens
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: us-east-1
        run: aws sts get-caller-identity