name: Cli Release Token Validation
on:
  workflow_dispatch:

jobs:
  token-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Validate REPO_ACCESS_TOKEN
        uses: actions/checkout@v2
        with:
          repository: '${{ github.repository_owner }}/twilio-oai'
          token:  ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: Validate AWS tokens
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ACCESS_ROLE}}
          aws-region: us-east-1
