name: Slack Notification

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Cli Release
    branches: [main]
    types:
      - completed
jobs:
  wait-for-releases:
    name: Wait for Docker, Homebrew, RPM and Platform executables Release
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        id: extract_branch
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      - name: Wait for Docker Release
        uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: twilio
          repo: twilio-cli
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          workflow_file_name: docker-release.yml
          ref: ${{steps.extract_branch.outputs.branch}}
          wait_interval: 10
          trigger_workflow: false
          wait_workflow: true
      - name: Wait for Oclif Release
        uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: twilio
          repo: twilio-cli
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          workflow_file_name: oclif-release.yml
          ref: ${{steps.extract_branch.outputs.branch}}
          wait_interval: 10
          trigger_workflow: false
          wait_workflow: true
      - name: Wait for Platform Executables Release
        uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: twilio
          repo: twilio-cli
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          workflow_file_name: platform-executables.yml
          ref: ${{steps.extract_branch.outputs.branch}}
          wait_interval: 10
          trigger_workflow: false
          wait_workflow: true
      - name: Wait for RPM Build
        uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: twilio
          repo: twilio-cli
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          workflow_file_name: rpmbuild.yml
          ref: ${{steps.extract_branch.outputs.branch}}
          wait_interval: 10
          trigger_workflow: false
          wait_workflow: true
  notify-complete-success:
    needs: [ wait-for-releases ]
    name: Notify Release Completed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEB_HOOK }}
          SLACK_COLOR: "#36a64f"
          SLACK_USERNAME: CLI Release Bot
          SLACK_ICON_EMOJI: ":ship:"
          SLACK_TITLE: 'Twilio CLI'
          SLACK_MESSAGE: 'Release Completed.'
          MSG_MINIMAL: actions url
